---
title: "git_00"
author: "Shontra Holland"
date: "09/09/21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  

“Beware the Jabberwock, my son!  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
I have been one acquainted with the night.  
I have walked out in rain—and back in rain.  
I have outwalked the furthest city light. 

I have looked down the saddest city lane.  
I have passed by the watchman on his beat  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  


## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
You wanna know what happened to Elvis  
I’ll tell you what happened  
I oughta know man I was one of his army  
I mean man I was on his side  
He made us feel all right  
We were the first wave in the  
Postwar baby boom    
The generation before had just come  
Out of the Great Depression and World War II  
You know heavy vibes for people to wear  
So much heaviness like some kind of  
Voiding of the emotions  
 
Their music you know the songs  
Life always carries  
You know every culture has songs  
Well anyway their music was  
Restrained emotion  
You know like you didn’t wanna dance  
If you didn’t know how  
